### ISSUE TITLE
Convert Installation and Configuration Guide to Markdown

### ISSUE THREAD

**Issue by drew-russell** [rubrikinc/rubrik-integration-for-servicenow#2]
**What would you like to be added**:

Convert the, or maybe create a copy, of the Rubrik Scoped Certified Application Installation and Configuration Guide to Markdown.

**Why is this needed**:

Allow for easier PRs against the Guide

**Comment by rfitzhugh** [comment]
@railroadmanuk if you can share the original .doc or .docx file with me, I'll convert to markdown.

**Comment by railroadmanuk** [comment]
We have to have this in docx format, and in ServiceNOW's template to push to their store. If we convert to markdown then this conversion would need updating as well as the docx version each time we make a change to the app. This seems unnecessary to me. The PDF is just in this repo so we can link to it from the ServiceNOW store homepage.

**Comment by rfitzhugh** [comment]
Is this repo solely intended for hosting that PDF? If so, then we should evaluate storing this PDF elsewhere.

**Comment by drew-russell** [comment]
There is benefit in converting the file to markdown to allow better collaboration with the community. Currently, if there is a bug in the documentation there is no easy way to suggest changes / fix that bug.

We may need to re-format the document a big but there are plenty of tools that can handle the markdown -> PDF conversion process for us.
